Vagrant.configure("2") do |config|
	config.vm.box = "bento/centos-7.7"
	config.vm.provider "parallels" do |prl|
		prl.name = 'k8s_master'
		prl.update_guest_tools = true

		prl.memory = 2048
		prl.cpus = 2
	end
end
